config/routes.rb
Rails.application.routes.draw do
  
  resources :members do
    resources :account_numbers, only: [:new, :create]
    resources :alerts
    resources :requests
  end
  devise_for :users
  root 'pages#home'
  get '/search', to: 'search#search'
  get '/user_assigned', to: 'pages#user_assigned'
  get '/users', to: 'pages#users'
  get '/alerts', to: 'pages#index'
  get '/requests', to: 'pages#requests'
  resources :documents
  resources :request_templates
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/request_template.rb
class RequestTemplate < ApplicationRecord
    has_paper_trail
end

app/controllers/request_templates_controller.rb
class RequestTemplatesController < ApplicationController
  before_action :set_request_template, only: %i[ show edit update destroy ]
  before_action :set_documents

  # GET /request_templates or /request_templates.json
  def index
    @request_templates = RequestTemplate.all
  end

  # GET /request_templates/1 or /request_templates/1.json
  def show
  end

  # GET /request_templates/new
  def new
    @request_template = RequestTemplate.new
  end

  # GET /request_templates/1/edit
  def edit
  end

  # POST /request_templates or /request_templates.json
  def create
    @request_template = RequestTemplate.new(request_template_params)

    respond_to do |format|
      if @request_template.save
        format.html { redirect_to request_template_url(@request_template), notice: "Request template was successfully created." }
        format.json { render :show, status: :created, location: @request_template }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /request_templates/1 or /request_templates/1.json
  def update
    respond_to do |format|
      if @request_template.update(request_template_params)
        format.html { redirect_to request_template_url(@request_template), notice: "Request template was successfully updated." }
        format.json { render :show, status: :ok, location: @request_template }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_templates/1 or /request_templates/1.json
  def destroy
    @request_template.destroy!

    respond_to do |format|
      format.html { redirect_to request_templates_url, notice: "Request template was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_documents
        @documents = Document.all 
    end
    def set_request_template
      @request_template = RequestTemplate.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def request_template_params
      params.require(:request_template).permit(:subject, :greeting, :greeting_line_two, :step_one, :step_two, :footer_header, :complete_by, :questions, :hours_of_operation, :email, :phone_numbers, :call_to_action, :incomplete, :request, :product, :rfi_date)
    end
end

app/helpers/request_templates_helper.rb
module RequestTemplatesHelper
end

app/views/request_templates/_form.html.erb
<%= form_with(model: request_template) do |form| %>
    <% if request_template.errors.any? %>
        <div style="color: red">
            <h2><%= pluralize(request_template.errors.count, "error") %> prohibited this request_template from being saved:</h2>

            <ul>
                <% request_template.errors.each do |error| %>
                <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="row">
        <div class="col-2"><p>
            <%= form.label :product, style: "display:block"%></p>
        </div>
        <div class="col-10"><p>
            <%= form.select :product, [["Deposit"],["Credit Card"],["Other"]], include_blank: 'Please Select', selected: @request_template.product, class: "col-12"%></p>
        </div>
    </div>
    <div class="row">
        <div class="col-2"><p>
            <%= form.label :request, style: "display:block"%></p>
        </div>
        <div class="col-10"><p>
            <%= form.select :request, [["RFI"],["Other"]], include_blank: 'Please Select', selected: @request_template.request, class: "col-12"%></p>
        </div>
    </div>
    <div class="row">
        <div class="col-2"><p>
            <%= form.label :rfi_date, style: "display:block"%></p>
        </div>
        <div class="col-10"><p>
            <%=form.number_field :rfi_date, class: "col-1"%></p>
        </div>
    </div>
    <div class="row">
        <div class="col-2"><p>
            <%= form.label :subject, style: "display:block"%></p>
        </div>
        <div class="col-10"><p>
            <%=form.text_field :subject, class: "col-12"%></p>
        </div>
    </div>
    <div class="row">
        <div class="col-2"><p>
            <%= form.label :greeting, style: "display:block"%></p>
        </div>
        <div class="col-10"><p>
            <%=form.text_field :greeting, class: "col-12"%></p>
        </div>
    </div>
    <div class="row">
        <div class="col-2"><p>
            <%= form.label :greeting_line_two, style: "display:block"%></p>
        </div>
        <div class="col-10"><p>
            <%=form.text_field :greeting_line_two, class: "col-12"%></p>
        </div>
    </div>
    <div class="row">
        <div class="col-2"><p>
            <%= form.label :call_to_action, style: "display:block"%></p>
        </div>
        <div class="col-10"><p>
            <%=form.text_field :call_to_action, class: "col-12"%></p>
        </div>
    </div>
    <div class="row">
        <div class="col-2"><p>
            <%= form.label :step_one, style: "display:block"%></p>
        </div>
        <div class="col-10"><p>
            <%=form.text_area :step_one, class: "col-12"%></p>
        </div>
    </div>
    <div class="row">
        <div class="col-2"><p>
            <%= form.label :step_two, style: "display:block"%></p>
        </div>
        <div class="col-10"><p>
            <%=form.text_area :step_two, class: "col-12"%></p>
        </div>
    </div>
    <div class="row">
        <div class="col-2"><p>
            <%= form.label :footer_header, style: "display:block"%></p>
        </div>
        <div class="col-10"><p>
            <%=form.text_field :footer_header, class: "col-12"%></p>
        </div>
    </div> 
    <div class="row">
        <div class="col-2"><p>
            <%= form.label :complete_by, style: "display:block"%></p>
        </div>
        <div class="col-10"><p>
            <%=form.text_field :complete_by, class: "col-12"%></p>
        </div>
    </div>
    <div class="row">
        <div class="col-2"><p>
            <%= form.label :incomplete, style: "display:block"%></p>
        </div>
        <div class="col-10"><p>
            <%=form.text_field :incomplete, class: "col-12"%></p>
        </div>
    </div>
    <div class="row">
        <div class="col-2"><p>
            <%= form.label :questions, style: "display:block"%></p>
        </div>
        <div class="col-10"><p>
            <%=form.text_area :questions, class: "col-12"%></p>
        </div>
    </div>
    <div class="row">
        <div class="col-2"><p>
            <%= form.label :hours_of_operation, style: "display:block"%></p>
        </div>
        <div class="col-10"><p>
            <%=form.text_field :hours_of_operation, class: "col-12"%></p>
        </div>
    </div> 
    <div class="row">
        <div class="col-2"><p>
            <%= form.label :email, style: "display:block"%></p>
        </div>
        <div class="col-10"><p>
            <%=form.text_field :email, class: "col-12"%></p>
        </div>
    </div>
    <div class="row">
        <div class="col-2"><p>
            <%= form.label :phone_numbers, style: "display:block"%></p>
        </div>
        <div class="col-10"><p>
            <%=form.text_field :phone_numbers, class: "col-12"%></p>
        </div>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/request_templates/_request_template.html.erb
<div id="<%= dom_id request_template %>">
</div>

app/views/request_templates/edit.html.erb
<div class="container">
    <div class="row mx-1">
        <h1>Editing Request Template</h1>
        <div class="row", id="documents">
            <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
                <%= render "form", request_template: @request_template %>
            </div>
        </div>
    </div>
    <div>
        <%= link_to "Back to template", @request_template, class: "btn btn-outline-primary shadow" %> |
    </div>
</div>

app/views/request_templates/index.html.erb
<div class="container">
    <div class="row mx-1">
        <h1>Request templates</h1>
        <div class="col-2">
            <%= link_to "New request template", new_request_template_path, class: "btn btn-outline-primary shadow" %>
        </div>
        <br><br>
        <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
            <table class="table table-striped table-bordered shadowed">
                <thead>
                    <tr>
                        <th>Request Template Type</th>
                        <th>Product</th>
                        <th>Request</th>
                        <th>Days</th>
                    </tr>
                </thead>
                <tbody>
                    <% @request_templates.each do |request_template| %>
                        <tr>
                            <td><%=link_to request_template.subject, request_template %></td>
                            <td><%=request_template.product%></td>
                            <td><%=request_template.request%></td>
                            <td><%=request_template.rfi_date%></td>
                        </tr>
                    <%end%>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/request_templates/new.html.erb
<div class="container">
    <div class="row mx-1">
        <h1>New Request Template</h1>
        <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
            <%= render "form", request_template: @request_template %>
        </div>
        <div>
            <%= link_to "Back to templates", request_templates_path, class: "btn btn-outline-primary shadow"%>
        </div>
    </div>
</div>

app/views/request_templates/show.html.erb
<div class="container">
<br><br>
    <div class="row mx-1">
    <br>
        <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
            <h3>Subject: <%=@request_template.subject%></h3>
            <br>
            <p><%=@request_template.greeting%></p>
            <p><%=@request_template.greeting_line_two%></p>
            <br>
            <p style="color:darkblue;"><strong><%=@request_template.call_to_action%></strong></p>
            <p><span style="font-weight: bold; color: darkorange;">Step One: </span><%=@request_template.step_one%></p>
            <p><span style="font-weight: bold; color: darkorange;">Step Two: </span><%=@request_template.step_two%></p>
            <div class="mx-1">
                <% @documents.each do |doc|%>
                    <p style="color:darkred; font-style:italic;">if <%=doc.document_type%> is required</p>
                    <p><strong><%=doc.document_description%></strong></p>
                    <ul>
                        <%if doc.requirement1_required == true%>
                            <div><%= str = "\u2022" + " " +doc.requirement1%></div>
                        <%end%>
                        <%if doc.requirement2_required == true%>
                            <div><%= str = "\u2022" + " " +doc.requirement2%></div>
                        <%end%>
                        <%if doc.requirement3_required == true%>
                            <div><%= str = "\u2022" + " " +doc.requirement3%></div>
                        <%end%>
                        <%if doc.requirement4_required == true%>
                            <div><%= str = "\u2022" + " " +doc.requirement4%></div>
                        <%end%>
                    </ul>
                <%end%>
            </div>
            <div style="background-color:lightgrey; margin:50px;text-align:center; color:darkblue;">
                <br><p><strong><%=@request_template.footer_header%></strong></p>
                <%=@request_template.complete_by %> <%= (Date.today + @request_template.rfi_date).strftime("%m/%d/%Y")%>.<br>
                <%=@request_template.incomplete%><br>
                <br>
            </div>
            <p><span style="font-weight: bold; color: darkorange;">Questions?</span></p>
            <%=str = "\u2022" + " " +@request_template.questions%> <%=@request_template.hours_of_operation%><br>
            <%=str = "\u2022" + " " +@request_template.email%> <%=@request_template.phone_numbers%>

        </div>
        <div>
        <%= link_to "Edit this request template", edit_request_template_path(@request_template), class: "btn btn-outline-info shadow"  %> |
        <%= link_to "Back to request templates", request_templates_path, class: "btn btn-outline-primary shadow" %>

        <%= button_to "Destroy this request template", @request_template, method: :delete, form: { data: {turbo_confirm: "Are you sure?"}}, class: "btn btn-outline-danger shadow mt-2"%>
        </div>
    </div>
</div>