config/routes.rb
Rails.application.routes.draw do
  
  resources :members do
    resources :account_numbers, only: [:new, :create]
    resources :alerts
    resources :requests
  end
  devise_for :users
  root 'pages#home'
  get '/search', to: 'search#search'
  get '/user_assigned', to: 'pages#user_assigned'
  get '/users', to: 'pages#users'
  get '/alerts', to: 'pages#index'
  get '/requests', to: 'pages#requests'
  resources :documents
  resources :request_templates
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/account_number.rb
class AccountNumber < ApplicationRecord
  belongs_to :member, inverse_of: :account_numbers

end

app/models/alert.rb
class Alert < ApplicationRecord
  belongs_to :member, inverse_of: :alerts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
    has_paper_trail
    has_many :request_documents
    has_many :requests, through: :request_documents
end

app/models/member.rb
class Member < ApplicationRecord
    validates :first_name, :presence => true
    validates :last_name, :presence => true

    has_many :account_numbers, dependent: :destroy, inverse_of: :member
    accepts_nested_attributes_for :account_numbers

    has_many :alerts, dependent: :destroy, inverse_of: :member
    accepts_nested_attributes_for :alerts

    has_many :requests, dependent: :destroy, inverse_of: :member
    accepts_nested_attributes_for :requests
    
    def full_name
        "#{first_name} #{last_name}".titleize
    end
    
end

app/models/request.rb
class Request < ApplicationRecord
    has_many :request_documents
    has_many :documents, through: :request_documents
    belongs_to :member, inverse_of: :requests
    accepts_nested_attributes_for :request_documents, allow_destroy: true
end

app/models/request_document.rb
class RequestDocument < ApplicationRecord
  belongs_to :request
  belongs_to :document

end

app/models/request_template.rb
class RequestTemplate < ApplicationRecord
    has_paper_trail
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: %i[ show edit update destroy ]
  before_action :set_member, only: %i[ create ]

  # GET /alerts or /alerts.json
  def index
    @alerts = Alert.all
  end

  # GET /alerts/1 or /alerts/1.json
  def show

  end
 
  # GET /alerts/new
  def new
    set_member
    @alert = @member.alerts.build
    # @alert = Alert.new
  end

  # GET /alerts/1/edit
  def edit
    @member = @alert.member
  end

  # POST /alerts or /alerts.json
  def create
    set_member
    # @alert = Alert.new(alert_params)
    @alert = @member.alerts.build(alert_params)

    respond_to do |format|
      if @alert.save
        format.html { redirect_to member_alert_path(@member, @alert), notice: "Alert was successfully created." }
        format.json { render :show, status: :created, location: @alert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alerts/1 or /alerts/1.json
  def update
    respond_to do |format|
      if @alert.update(alert_params)
        format.html { redirect_to member_alert_path, notice: "Alert was successfully updated." }
        format.json { render :show, status: :ok, location: @alert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1 or /alerts/1.json
  def destroy
    @alert.destroy!
    @member = @alert.member
    respond_to do |format|
      format.html { redirect_to @member, notice: "Alert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_member
        @member = Member.find(params[:member_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def alert_params
      params.require(:alert).permit(:member_id, :assigned_to, :date_of_notice, :received_from, :type_of_review, :date_oldest_account, :decision, :monitor_until, :fca_maintain, :document_request, :date_documents_requested, :documents_received, :fdra_facts_notes, :olb_review_by_lr, :background_review_by_lr, :fraud_flags, :idv_docs_received, :loss, :exposure, :funds_returned_reason, :external_account)
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
    @member = Member.find(params[:id])
    @accounts = @member.account_numbers
    @alerts = @member.alerts
  end

  # GET /members/new
  def new
    @member = Member.new
    @member.account_numbers.build
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to member_url(@member)}
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_url(@member), notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy!

    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.fetch(:member, {}).permit(:first_name, :last_name, :email, account_numbers_attributes: [:id, :number, :account_type])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    ALERTS_PER_PAGE = 25
  def index
    @page = params.fetch(:page,0).to_i
    @alerts = Alert.includes(:member).offset(@page*ALERTS_PER_PAGE).limit(ALERTS_PER_PAGE)
  end
  def user_assigned
    @user = current_user
    @page = params.fetch(:page,0).to_i
    @alerts = Alert.includes(:member).offset(@page*ALERTS_PER_PAGE).limit(ALERTS_PER_PAGE)
  end
  def users
    @users = User.all
  end
  def requests 
    @page = params.fetch(:page,0).to_i
    @requests = Request.includes(:member).offset(@page*ALERTS_PER_PAGE).limit(ALERTS_PER_PAGE)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

    def search
        if params[:query].present?
            @members = Member.where("first_name LIKE ? OR last_name LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%").find_each
            @numbers = AccountNumber.where(number: params[:query]).find_each
        else
            @members = Member.none
        end
    end

end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/members_helper.rb
module MembersHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/search_helper.rb
module SearchHelper
    
end

app/views/layouts/_footer.html.erb
<div class="fixed-bottom lead", id="footer">
"Fandral (Fraud and Restricted Account Log) © 2024 Shaun® All rights reserved. Version 0.1"
</div>

app/views/layouts/_messages.html.erb
<div class="container mt-10">
    <% flash.each do |name,msg|%>
        <%if flash[:notice]%>
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <%= msg %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        <%else%>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <%= msg %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        <%end%>
    <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg" data-bs-theme="dark" potision="fixed">
    <div class="container-fluid">
        <a class="navbar-brand" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample"><%=image_tag("lr_logo.png", :class => "lr_logo")%></a>
        <a class="app_name my-auto pe-1 link-offset-2 link-underline link-underline-opacity-0", href="/">Fandral</a> 
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/members">Members</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/requests">RFI</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/alerts">Alerts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/user_assigned">My Alerts</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Admin
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="/documents">Documents</a></li>
                        <li><a class="dropdown-item" href="/request_templates">Request Templates</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="/members">Create New Alert</a></li>
                    </ul>
                </li>
            </ul>
            <form action="/search" method="get" class="d-flex me-2 b-2" >
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <% if user_signed_in? %>
                <%= link_to "My Profile", edit_user_registration_path, {class: "btn btn-primary me-md-2 my-2 text-nowrap"}%>
                <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-primary me-md-2 my-2 text-nowrap" %>
            <% else %>
                <%= link_to "New User", new_user_registration_path, {class: "btn btn-primary me-md-2 my-2 text-nowrap"} %>
                <%= link_to "Log In", new_user_session_path, {class: "btn btn-primary me-md-2 my-2 text-nowrap"}%>
            <%end%>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/_offcanvas.html.erb
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasExampleLabel">Offcanvas</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div>
      Some text as placeholder. In real life you can have the elements you have chosen. Like, text, images, lists, etc.
    </div>
    <div class="dropdown mt-3">
      <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
        Dropdown button
      </button>
      <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="#">Action</a></li>
        <li><a class="dropdown-item" href="#">Another action</a></li>
        <li><a class="dropdown-item" href="#">Something else here</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fandral</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <%= render "layouts/messages"%>
    <%= yield %>  
    <%= render "layouts/footer"%>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<h1>About this app</h1>
<br>
<p>Members can be created from the Members index page.</p>
<p>Members will require 1 account number at the start, additional accounts can be created later.</p>
<p>In the future, this information will be obtained via api for all members, and will not require creating records.</p>
<p>The member show page contains information on Alerts, Requests, Accounts and Member information.</p>
<p>From this page, you can add accounts, create alerts and create requests.</p>
<p>Alerts contain fields for all data points required to be tracked.</p>
<p>Requests can be made for documents from this page.</p>
<p>Requests contain a product, and document(s) required.</p>
<p>Once submitted, an email, and follow up emails, are sent to the member.</p>
<p>This email will contain a template sent to all members, language that relates to each document, and a submit by date that depends on the product type.</p>

<p>The member is then presented with an interface to upload documents.</p>
<p>The banker side then shows recent documents submitted for review.</p>
<p>The banker can then forward the document through email to IDV. Or IDV can be given limited access to the application, that allows them to see the member name / application ID and the document for review.</p>
<p>When the documents are uploaded, emails will stop.</p>
<p>Requests will time out after a set time.</p>

app/views/pages/index.html.erb
<div class="container">
    <h1>Alerts</h1>
    <h5 class="lead">Create new alerts from the Member's page.</h5>
        <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Member</th>
                        <th>Assigned To</th>
                        <th>Alert Type</th>
                        <th>Days Open</th>
                        <th>Date Created</th>
                    </tr>
                </thead>
                <tbody>
                    <% @alerts.each do |alert|%>
                    <tr>
                        <td><%= link_to alert.member.full_name, member_path(alert.member)%></td>
                        <td><%= alert.assigned_to %></td>
                        <td><%= alert.type_of_review %></td>
                        <td><%= ((Time.current - alert.created_at.beginning_of_day)/86400).to_i%></td>
                        <td><%= alert.created_at.strftime("%m-%d-%y")%></td>
                    </tr>
                    <%end%>
                </tbody>
            </table>
        <div class="row mx-auto">
            <p>Page <%= @page+1%></p>
        </div>
    </div>
    <div class="d-flex">
    <%=link_to "First Page", alerts_path(page: 0), class: "btn btn-outline-primary mx-2 shadow"%>
    <%=link_to "Previous Page", alerts_path(page: @page - 1), class: "btn btn-outline-primary mx-2 shadow"%>
    <%= link_to "Next Page", alerts_path(page: @page + 1), class: "btn btn-outline-primary mx-2 shadow"%>
    </div>
</div>

app/views/pages/requests.html.erb
<div class="container">
    <h1>Requests for Information</h1>
    <h5 class="lead">Create new requests from the Member's page.</h5>
        <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Member</th>
                        <th>Product Type</th>
                        <th>Days Open</th>
                        <th>Date Created</th>
                    </tr>
                </thead>
                <tbody>
                    <% @requests.each do |request|%>
                    <tr>
                        <td><%= link_to request.member.full_name, member_path(request.member)%></td>
                        <td><%= request.products_type %></td>
                        <td><%= ((Time.current - request.created_at.beginning_of_day)/86400).to_i%></td>
                        <td><%= request.created_at.strftime("%m-%d-%y")%></td>
                    </tr>
                    <%end%>
                </tbody>
            </table>
        <div class="row mx-auto">
            <p>Page <%= @page+1%></p>
        </div>
    </div>
    <div class="d-flex">
    <%=link_to "First Page", requests_path(page: 0), class: "btn btn-outline-primary mx-2 shadow"%>
    <%=link_to "Previous Page", requests_path(page: @page - 1), class: "btn btn-outline-primary mx-2 shadow"%>
    <%= link_to "Next Page", requests_path(page: @page + 1), class: "btn btn-outline-primary mx-2 shadow"%>
    </div>
</div>

app/views/pages/user_assigned.html.erb
<div class="container">
    <h1><%=@user.email%></h1>
        <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Member</th>
                        <th>Assigned to</th>
                        <th>Alert Type</th>
                        <th>Days Open</th>
                        <th>Date Created</th>
                    </tr>
                </thead>
                <tbody>
                    <%= Alert.where(assigned_to: @user.email).find_each do |alert|%>
                        <tr>
                            <td><%= link_to alert.member.full_name, alert.member %></td>
                            <td><%= alert.assigned_to%></td>
                            <td><%= alert.type_of_review %></td>
                            <td><%= ((Time.current - alert.created_at.beginning_of_day)/86400).to_i%></td>
                            <td><%= alert.created_at.strftime("%m-%d-%y")%></td>
                        </tr>
                    <%end%>
                </tbody>
            </table>
        <div class="row mx-auto">
            <p>Page <%= @page+1%></p>
        </div>
    </div>
    <div class="d-flex">
    <%=link_to "First Page", root_path(page: 0), class: "btn btn-outline-primary mx-2 shadow"%>
    <%=link_to "Previous Page", root_path(page: @page - 1), class: "btn btn-outline-primary mx-2 shadow"%>
    <%= link_to "Next Page", root_path(page: @page + 1), class: "btn btn-outline-primary mx-2 shadow"%>
    </div>
</div>

app/views/pages/users.html.erb
<ul>
  <% @users.each do |user| %>
    <li><%= user.email %></li>
  <% end %>
</ul>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
<h4 class="alert-heading"><%= pluralize(obj.errors.count, "error") %> prohibited this <%=obj.class.name.downcase%> from being saved:</h4>
    <ul>
        <% obj.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>