config/routes.rb
Rails.application.routes.draw do
  
  resources :members do
    resources :account_numbers, only: [:new, :create]
    resources :alerts
    resources :requests
  end
  devise_for :users
  root 'pages#home'
  get '/search', to: 'search#search'
  get '/user_assigned', to: 'pages#user_assigned'
  get '/users', to: 'pages#users'
  get '/alerts', to: 'pages#index'
  get '/requests', to: 'pages#requests'
  resources :documents
  resources :request_templates
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/document.rb
class Document < ApplicationRecord
    has_paper_trail
    has_many :request_documents
    has_many :requests, through: :request_documents
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
    before_action :set_document, only: %i[show edit update destroy]

    def index 
        @documents = Document.all 
    end

    def show
    end

    def new
        @document = Document.new 
    end

    def create 
        @document = Document.new(document_params)
        if @document.save
            redirect_to @document,
            notice: "Document was created successfully."
        else
            render :new 
        end
    end

    def edit
    end

    def update
        if @document.update(document_params)
            redirect_to @document,
            notice: "Document was updated successfully"
        else
            render :edit
        end
    end

    def destroy
        @document.destroy
        redirect_to documents_url,
        notice: "Document was deleted successfully"
    end

    private

    def set_document
        @document = Document.find(params[:id])
    end

    def document_params
        params.require(:document).permit(:document_type, :document_description, :requirement1, :requirement1_required, :requirement2, :requirement2_required, :requirement3, :requirement3_required, :requirement4, :requirement4_required)
    end


end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: @document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div style="color: red">
      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
    <div class="col-2"><p>
        <%= form.label :document_type, style: "display: block" %></p>
    </div>
    <div class="col-10"><p>
        <%= form.text_field :document_type %></p>
    </div>
</div>
<div class="row">
    <div class="col-2"><p>
        <%= form.label :document_description, style: "display: block" %></p>
    </div>
    <div class="col-10"><p>
        <%= form.text_area :document_description, class: "col-12 row-3" %></p>
    </div>
    <div class="col-2"><p>
        <%= form.label :requirement_one_required?, style: "display: block" %></p>
    </div>
    <div class="col-10"><p>
        <%= form.check_box :requirement1_required %></p>
    </div>
    <div id="requirement1", style="display:none;">
        <div class="row">
            <div class="col-2"><p>
                <%= form.label :requirement_one, style: "display: block" %></p>
            </div>
            <div class="col-10"><p>
                <%= form.text_area :requirement1, class: "col-12 row-3" %></p>
            </div> 
        </div> 
    </div>
    <div class="col-2"><p>
        <%= form.label :requirement_two_required?, style: "display:block;"%></p>    
    </div>
    <div class="col-10"><p>
        <%=form.check_box :requirement2_required%></p>
    </div>
    <div id="requirement2", style="display:none;">
        <div class="row">
            <div class="col-2"><p>
                <%=form.label :requirement_two, style: "display: block"%></p>
            </div>
            <div class="col-10"><p>
                <%=form.text_area :requirement2, class: "col-12 row-3"%></p>
            </div>
        </div>
    </div>
    <div class="col-2"><p>
        <%= form.label :requirement_three_required?, style: "display:block;"%></p>    
    </div>
    <div class="col-10"><p>
        <%=form.check_box :requirement3_required%></p>
    </div>
    <div id="requirement3", style="display:none;">
        <div class="row">
            <div class="col-2"><p>
                <%=form.label :requirement_three, style: "display: block"%></p>
            </div>
            <div class="col-10"><p>
                <%=form.text_area :requirement3, class: "col-12 row-3"%></p>
            </div>
        </div>
    </div>
    <div class="col-2"><p>
        <%= form.label :requirement_four_required?, style: "display:block;"%></p>    
    </div>
    <div class="col-10"><p>
        <%=form.check_box :requirement4_required%></p>
    </div>
    <div id="requirement4", style="display:none;">
        <div class="row">
            <div class="col-2"><p>
                <%=form.label :requirement_four, style: "display: block"%></p>
            </div>
            <div class="col-10"><p>
                <%=form.text_area :requirement4, class: "col-12 row-3"%></p>
            </div>
        </div>
    </div>
</div>
<div>
    <%= form.submit %>
</div>
<% end %>
<script type="text/javascript">
  var checkbox = document.getElementById('document_requirement1_required');
  var details_div = document.getElementById('requirement1');
  checkbox.onchange = function() {
     if(this.checked) {
       details_div.style['display'] = 'block';
     } else {
       details_div.style['display'] = 'none';
     }
  };
  var checkbox = document.getElementById('document_requirement2_required');
  var details_div2 = document.getElementById('requirement2');
  checkbox.onchange = function() {
     if(this.checked) {
       details_div2.style['display'] = 'block';
     } else {
       details_div2.style['display'] = 'none';
     }
  };
  var checkbox = document.getElementById('document_requirement3_required');
  var details_div3 = document.getElementById('requirement3');
  checkbox.onchange = function() {
     if(this.checked) {
       details_div3.style['display'] = 'block';
     } else {
       details_div3.style['display'] = 'none';
     }
  };
  var checkbox = document.getElementById('document_requirement4_required');
  var details_div4 = document.getElementById('requirement4');
  checkbox.onchange = function() {
     if(this.checked) {
       details_div4.style['display'] = 'block';
     } else {
       details_div4.style['display'] = 'none';
     }
  };
</script>

app/views/documents/edit.html.erb
<div class="container">
    <div class="row mx-1">
        <h1>Editing document</h1>
        <div class="row", id="documents">
            <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
                <%= render "form", document: @document %>
            </div>
        </div>
    </div>
    <div>
        <%= link_to "Back to document", document_path, class: "btn btn-outline-primary shadow" %> |
    </div>
</div>

app/views/documents/index.html.erb
<div class="container">
    <div class="row mx-1">
        <h1>Documents</h1>
        <div class="col-2">
            <%= link_to "New Document", new_document_path, class: "btn btn-outline-primary shadow" %>
        </div>
        <br><br>
            <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
                <table class="table table-striped table-bordered shadowed">
                    <thead>
                        <tr>
                            <th>Document Type</th>
                            <th>Document Description</th>
                            <th>Last Updated</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @documents.each do |document| %>
                            <tr>
                                <td><%=link_to document.document_type, document %></td>
                                <td><%=document.document_description%></td>
                                <td><%=document.updated_at.strftime("%m-%d-%y")%>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/documents/new.html.erb
<div class="container">
    <div class="row mx-1">
        <h1>New alert</h1>
        <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
            <%= render "form", document: @document %>
        </div>
        <div>
            <%= link_to "Back to documents", documents_path, class: "btn btn-outline-primary shadow"%>
        </div>
    </div>
</div>

app/views/documents/show.html.erb
<div class="container">
    <div class="row mx-1">
        <h1><%= @document.document_type%></h1>
        <p>The following text will be displayed in the email to the member, when this document type is included in a request.</p>
        <div class="row", id="documents">
            <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
                <strong><%= @document.document_type%></strong><br>
                <%= @document.document_description %><br>
                <ul>
                    <%if @document.requirement1_required == true%>
                        <div><%=str = "\u2022" + @document.requirement1%></div>
                    <%end%>
                    <%if @document.requirement2_required == true%>
                        <div><%=str = "\u2022" +@document.requirement2%></div>
                    <%end%>
                    <%if @document.requirement3_required == true%>
                        <div><%=str = "\u2022" +@document.requirement3%></div>
                    <%end%>
                    <%if @document.requirement4_required == true%>
                        <div><%=str = "\u2022" +@document.requirement4%></div>
                    <%end%>
                </ul>
            </div>
        </div>
        <div>
        <%= link_to "Edit this document", edit_document_path, class: "btn btn-outline-info shadow" %> |
        <%= link_to "Back to Documents", "/documents", class: "btn btn-outline-primary shadow" %>

        <%= button_to "Destroy this document", document_path(@document), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: "btn btn-outline-danger shadow mt-2"%>
        </div>
    </div>
</div>