config/routes.rb
Rails.application.routes.draw do
  
  resources :members do
    resources :account_numbers, only: [:new, :create]
    resources :alerts
    resources :requests
  end
  devise_for :users
  root 'pages#home'
  get '/search', to: 'search#search'
  get '/user_assigned', to: 'pages#user_assigned'
  get '/users', to: 'pages#users'
  get '/alerts', to: 'pages#index'
  get '/requests', to: 'pages#requests'
  resources :documents
  resources :request_templates
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/member.rb
class Member < ApplicationRecord
    validates :first_name, :presence => true
    validates :last_name, :presence => true

    has_many :account_numbers, dependent: :destroy, inverse_of: :member
    accepts_nested_attributes_for :account_numbers

    has_many :alerts, dependent: :destroy, inverse_of: :member
    accepts_nested_attributes_for :alerts

    has_many :requests, dependent: :destroy, inverse_of: :member
    accepts_nested_attributes_for :requests
    
    def full_name
        "#{first_name} #{last_name}".titleize
    end
    
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
    @member = Member.find(params[:id])
    @accounts = @member.account_numbers
    @alerts = @member.alerts
  end

  # GET /members/new
  def new
    @member = Member.new
    @member.account_numbers.build
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to member_url(@member)}
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_url(@member), notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy!

    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.fetch(:member, {}).permit(:first_name, :last_name, :email, account_numbers_attributes: [:id, :number, :account_type])
    end

end

app/helpers/members_helper.rb
module MembersHelper

end

app/views/members/_form.html.erb
<div class="row mx-1">
    <div class="mx-auto border border-black mt-5 shadow p-3 mb-5 bg-body-tertiary rounded", id="user_card">
        <%= form_with(model: member, local: true) do |f| %>
            <div class="container text-start">   
                <% if member.errors.any? %>
                    <div style="color: red">
                        <ul>
                            <% member.errors.each do |error| %>
                                <li><%= error.full_message %></li>
                            <% end %>
                        </ul>
                    </div>
                <% end %>
            </div>
            <div class="field">
                <%=f.label :first_name %>
                <%=f.text_field :first_name, autofocus: true, autocomplete: "name", class: "w-100 border border-black shadow p-2", placeholder: "Enter the Member's first name here"%>
            </div>
            <div class="field">
                <%=f.label :last_name %>
                <%=f.text_field :last_name, autofocus: true, autocomplete: "name", class: "w-100 border border-black shadow p-2", placeholder: "Enter the Member's flast name here"%>
            </div>
            <div class="field">
                <%=f.label :email %>
                <%=f.email_field :email, autofocus: true, autocomplete: "name", class: "w-100 border border-black shadow p-2", placeholder: "Enter the Member's email here"%>
            </div>
                <%# <%=f.fields_for :account_numbers do |account_form| %>
                    <%# <div> %>
                        <%# <%=account_form.label :account_number %>
                    <%# </div> %>
                    <%# <div> %>
                        <%# <%=account_form.text_field :number %>
                    <%# </div> %>
                    <%# <div> %>
                        <%# <%=account_form.label :account_type %>
                    <%# </div> %>
                    <%# <div> %>
                        <%# <%=account_form.select :account_type, options_for_select([['Primary','primary'],['Secondary','secondary']]) %>
                    <%# </div> %>
                <%# <%end%>
            <br>
            <div>
                <%= f.submit %>
            </div>
        <% end %>
    </div>
</div>

app/views/members/_member.html.erb
<div id="<%= dom_id member %>">
</div>

app/views/members/edit.html.erb
<div class="container text-center">
    <h1>Editing member</h1>
    <%= render "form", member: @member %>
    <br>
    <div>
    <%= link_to "Show this member", @member %> |
    <%= link_to "Back to members", members_path %>
    </div>
</div>

app/views/members/index.html.erb
<div class="container">
    <div class="row mx-1">
        <h1>Members</h1>
        <div class="col-2">
            <%= link_to "New member", new_member_path, class: "btn btn-outline-primary shadow" %>
        </div>
        <br><br>
            <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
                <table class="table table-striped table-bordered shadowed">
                    <thead>
                        <tr>
                            <th>Member Name</th>
                            <th>alerts</th>
                            <th>Date Added</th>
                            <th>Date Updated</th>

                        </tr>
                    </thead>
                    <tbody>
                        <% @members.each do |member| %>
                            <%= render member %>
                            <tr>
                                <td><%=link_to member.full_name, member %></td>
                                <td><%= member.alerts.count %></td>
                                <td><%= member.created_at.strftime("%m-%d-%y") %></td>
                                <td><%=member.updated_at.strftime("%m-%d-%y") %></td>

                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/members/new.html.erb
<div class="container text-center">
    <h1>New Member</h1>
    <%= render "form", member: @member %>
    <br>
    <div>
    <%= link_to "Back to members", members_path %>
    </div>
</div>

app/views/members/show.html.erb
<%= turbo_frame_tag "request_modal"%>
<div class="container">
    <%= render @member %>
    <div class="border-bottom">
        <h1><%= @member.full_name%></h1>
    </div>
    <br>
    <div class="border-bottom">
        <h3>Alerts</h3>
        <div class="container">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Alert ID</th>
                        <th>Member ID</th>
                        <th>Days Open</th>
                        <th>Date Created</th>
                    </tr>
                </thead>
                <tbody>
                    <% @member.alerts.each do |alert|%>
                    <tr>
                        <td><%= link_to alert.id, member_alert_path(@member, alert)%></td>
                        <td><%= alert.member.id %></td>
                        <td><%= ((Time.current - alert.created_at.beginning_of_day)/86400).to_i%></td>
                        <td><%= alert.created_at.strftime("%m-%d-%y")%></td>
                    </tr>
                    <%end%>
                </tbody>
            </table>
            <%= link_to "Add New Alert", new_member_alert_path(@member), class: "btn btn-outline-primary shadow" %>
        </div>
        <br>
    </div>
    <br> 
    <div class="border-bottom">
        <h3>Request For Information</h3>
        <div class="container">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Request Type</th>
                        <th>Product</th>
                        <th>Days Open</th>
                        <th>Date Sent</th>
                    </tr>
                </thead>
                <tbody>
                    <% @member.requests.each do |request|%>
                        <tr>
                            <td><%= link_to request.request_type, member_request_path(@member, request)%></td>
                            <td><%= request.products_type %></td>
                            <td><%= ((Time.current - request.created_at.beginning_of_day)/86400).to_i%></td>
                            <td><%= request.created_at.strftime("%m-%d-%y")%></td>
                        </tr>
                    <%end%>
                </tbody>
            </table>
            <%= link_to "Generate New Request", new_member_request_path(@member), class: "btn btn-outline-primary shadow", data: {turbo_frame: "request_modal"} %>
        </div>
        <br>
    </div>
    <br>
    <div class="border-bottom">
        <h3>Accounts</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Account Numbers</th>
                    <th>Account Type</th>
                </tr>
            </thead>
            <tbody>
                <% @accounts.each do |number|%>
                <tr>
                    <td><%= number.number %></td>
                    <td><%= number.account_type%></td>
                </tr>
                <%end%>
            </tbody>
        </table>
        <div class="me-auto">
            <div class="row">
                <%= form_with(model: [@member, @member.account_numbers.build]) do |form|%>
                        <%=form.label :number %>
                        <%=form.text_field :number, class: "shadow"%>
                        <%=form.label :account_type, class: "ms-2"%>
                        <%=form.select :account_type,  options_for_select([['Primary','primary'],['Secondary','secondary']]), include_blank: 'Please Select', class: "shadow"%>
                <%= form.submit 'Add Account', class: "btn btn-outline-primary ms-2 shadow"%>
            </div>
            <%end%>
            <br>
        </div>
    </div>
    <div class="border-bottom pt-5">
        <%= link_to "Edit this member", edit_member_path(@member), class: "btn btn-outline-info shadow" %> |
        <%= link_to "Back to members", members_path, class: "btn btn-outline-primary shadow" %>
        <br><br>
        <%= button_to "Delete member", @member, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: "btn btn-outline-danger shadow" %>
        <br>
    </div>
</div>